redis:
    image: crosbymichael/redis
    container_name: redis

custom_redis_ambassador:
    image: svendowideit/ambassador
    container_name: custom_redis_ambassador
    ports:
     - 6379:6379
    links:
     - redis:redis

