#!/bin/bash
GIT_WORK_TREE=/home/vinay/Desktop/sem3/devops/HW/HW4/part3/deploy/green-www git checkout -f
docker pull localhost:5000/dockerdeployimage:latest
docker rm  -f dockerappgreen
docker rmi localhost:5000/dockerdeployimage:current
docker tag localhost:5000/dockerdeployimage:latest localhost:5000/dockerdeployimage:current
docker run -p 9876:8080 -d --name dockerappgreen localhost:5000/dockerdeployimage:latest
